backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
collections:
  - name: experiences
    label: Experiences
    folder: content/experiences
    create: false
    path: "{{slug}}/index"
    sortable_fields: ["weight", "title"]
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetime
        comment: This isn’t actually shown on the page.
      - name: weight
        label: Weight
        widget: number
        value: int
        comment: Lower comes first.
      - name: status
        label: Status
        widget: select
        options: ["closed", "partially open", "open"]
      - name: info
        label: Info URL
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: overview
    label: Overview
    files:
      - label: Main
        name: main
        file: content/_index.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: description
            label: Description
            widget: string
          - name: status
            label: Status
            options: ["closed", "partially open", "open"]
          - name: date
            label: Updated
            widget: date
            format: YYYY-MM-DD
